name: Setup new machine

on: push

jobs:
  deploy-dotfiles:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: ./settings.sh
      - run: ./install_apt.sh
      - run: ./install_brew.sh
      - run: ./install.sh
